const routes = [
  {
    path: '/',
    component: 'HomePage',
    label: 'Home',
    navLabel: 'Home',
    showInNav: true,
    changefreq: 'weekly',
    priority: 1.0,
  },
  {
    path: '/home',
    component: 'HomePage',
    label: 'Home Alias',
    showInNav: false,
    changefreq: 'monthly',
    priority: 0.5,
  },
  {
    path: '/decoder',
    component: 'Decoder',
    label: 'Decoder',
    navLabel: 'Decoder',
    showInNav: true,
    changefreq: 'monthly',
    priority: 0.8,
  },
  {
    path: '/endorsement-generator',
    component: 'EndorsementGenerator',
    label: 'Endorsement Generator',
    navLabel: 'Endorsement',
    showInNav: true,
    changefreq: 'weekly',
    priority: 0.9,
  },
  {
    path: '/wb',
    component: 'WeightBalanceCalculator',
    label: 'Weight & Balance',
    navLabel: 'W&B',
    showInNav: true,
    changefreq: 'monthly',
    priority: 0.8,
  },
  {
    path: '/flight-brief',
    component: 'FlightBrief',
    label: 'Flight Brief',
    navLabel: 'Brief',
    showInNav: true,
    changefreq: 'weekly',
    priority: 0.85,
  },
  {
    path: '/nighttime',
    component: 'NightTimeCalculator',
    label: 'Night Time Calculator',
    navLabel: 'Night',
    showInNav: true,
    changefreq: 'monthly',
    priority: 0.75,
  },
  {
    path: '/logbook',
    component: 'Logbook',
    label: 'Logbook',
    showInNav: false,
    changefreq: 'monthly',
    priority: 0.7,
  },
  {
    path: '/about',
    component: 'About',
    label: 'About',
    showInNav: false,
    changefreq: 'monthly',
    priority: 0.6,
  },
  {
    path: '/privacy',
    component: 'Privacy',
    label: 'Privacy',
    showInNav: false,
    changefreq: 'yearly',
    priority: 0.3,
  },
  {
    path: '/admin/notifications',
    component: 'AdminNotifications',
    label: 'Admin Notifications',
    showInNav: false,
    changefreq: 'monthly',
    priority: 0.2,
  },
];

module.exports = routes;
